
package br.gov.antaq.sip.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "sipPortType", targetNamespace = "sipns")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SipPortType {


    /**
     * 
     * @param senha
     * @param sigla
     * @param idOrgao
     * @param idContexto
     * @return
     *     returns boolean
     */
    @WebMethod(action = "sipnsAction")
    @WebResult(name = "returnAutenticar", partName = "returnAutenticar")
    public boolean autenticar(
        @WebParam(name = "IdOrgao", partName = "IdOrgao")
        String idOrgao,
        @WebParam(name = "IdContexto", partName = "IdContexto")
        String idContexto,
        @WebParam(name = "Sigla", partName = "Sigla")
        String sigla,
        @WebParam(name = "Senha", partName = "Senha")
        String senha);

}
