
package org.opensingular.requirement.connector.sei31.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SeiPortType", targetNamespace = "Sei")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SeiPortType {


    /**
     * Geracao de processos
     * 
     * @param unidadesEnvio
     * @param sinManterAbertoUnidade
     * @param siglaSistema
     * @param diasRetornoProgramado
     * @param textoMarcador
     * @param documentos
     * @param sinDiasUteisRetornoProgramado
     * @param identificacaoServico
     * @param idUnidade
     * @param sinEnviarEmailNotificacao
     * @param dataRetornoProgramado
     * @param procedimentosRelacionados
     * @param procedimento
     * @param idMarcador
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.RetornoGeracaoProcedimento
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public RetornoGeracaoProcedimento gerarProcedimento(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "Procedimento", partName = "Procedimento")
                    Procedimento procedimento,
            @WebParam(name = "Documentos", partName = "Documentos")
                    ArrayOfDocumento documentos,
            @WebParam(name = "ProcedimentosRelacionados", partName = "ProcedimentosRelacionados")
                    ArrayOfProcedimentoRelacionado procedimentosRelacionados,
            @WebParam(name = "UnidadesEnvio", partName = "UnidadesEnvio")
                    ArrayOfIdUnidade unidadesEnvio,
            @WebParam(name = "SinManterAbertoUnidade", partName = "SinManterAbertoUnidade")
                    String sinManterAbertoUnidade,
            @WebParam(name = "SinEnviarEmailNotificacao", partName = "SinEnviarEmailNotificacao")
                    String sinEnviarEmailNotificacao,
            @WebParam(name = "DataRetornoProgramado", partName = "DataRetornoProgramado")
                    String dataRetornoProgramado,
            @WebParam(name = "DiasRetornoProgramado", partName = "DiasRetornoProgramado")
                    String diasRetornoProgramado,
            @WebParam(name = "SinDiasUteisRetornoProgramado", partName = "SinDiasUteisRetornoProgramado")
                    String sinDiasUteisRetornoProgramado,
            @WebParam(name = "IdMarcador", partName = "IdMarcador")
                    String idMarcador,
            @WebParam(name = "TextoMarcador", partName = "TextoMarcador")
                    String textoMarcador);

    /**
     * Geracao de documentos
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param documento
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.RetornoInclusaoDocumento
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public RetornoInclusaoDocumento incluirDocumento(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "Documento", partName = "Documento")
                    Documento documento);

    /**
     * Lista de unidades disponiveis
     * 
     * @param identificacaoServico
     * @param idSerie
     * @param siglaSistema
     * @param idTipoProcedimento
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfUnidade
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfUnidade listarUnidades(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdTipoProcedimento", partName = "IdTipoProcedimento")
                    String idTipoProcedimento,
            @WebParam(name = "IdSerie", partName = "IdSerie")
                    String idSerie);

    /**
     * Lista de tipos de processo disponiveis
     * 
     * @param identificacaoServico
     * @param idSerie
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfTipoProcedimento
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfTipoProcedimento listarTiposProcedimento(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdSerie", partName = "IdSerie")
                    String idSerie);

    /**
     * Lista de series disponiveis
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param idTipoProcedimento
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfSerie
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfSerie listarSeries(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdTipoProcedimento", partName = "IdTipoProcedimento")
                    String idTipoProcedimento);

    /**
     * Lista de contatos
     * 
     * @param paginaAtual
     * @param sigla
     * @param identificacaoServico
     * @param idTipoContato
     * @param idContatos
     * @param idUnidade
     * @param siglaSistema
     * @param cpf
     * @param matricula
     * @param paginaRegistros
     * @param nome
     * @param cnpj
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfContato
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfContato listarContatos(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdTipoContato", partName = "IdTipoContato")
                    String idTipoContato,
            @WebParam(name = "PaginaRegistros", partName = "PaginaRegistros")
                    String paginaRegistros,
            @WebParam(name = "PaginaAtual", partName = "PaginaAtual")
                    String paginaAtual,
            @WebParam(name = "Sigla", partName = "Sigla")
                    String sigla,
            @WebParam(name = "Nome", partName = "Nome")
                    String nome,
            @WebParam(name = "Cpf", partName = "Cpf")
                    String cpf,
            @WebParam(name = "Cnpj", partName = "Cnpj")
                    String cnpj,
            @WebParam(name = "Matricula", partName = "Matricula")
                    String matricula,
            @WebParam(name = "IdContatos", partName = "IdContatos")
                    ArrayOfIdContatos idContatos);

    /**
     * Atualizacao de contatos
     * 
     * @param identificacaoServico
     * @param contatos
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String atualizarContatos(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "Contatos", partName = "Contatos")
                    ArrayOfContato contatos);

    /**
     * Consulta de processos
     * 
     * @param sinRetornarAndamentoGeracao
     * @param sinRetornarUltimoAndamento
     * @param siglaSistema
     * @param sinRetornarProcedimentosRelacionados
     * @param protocoloProcedimento
     * @param sinRetornarAssuntos
     * @param identificacaoServico
     * @param sinRetornarUnidadesProcedimentoAberto
     * @param idUnidade
     * @param sinRetornarAndamentoConclusao
     * @param sinRetornarProcedimentosAnexados
     * @param sinRetornarInteressados
     * @param sinRetornarObservacoes
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.RetornoConsultaProcedimento
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public RetornoConsultaProcedimento consultarProcedimento(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento,
            @WebParam(name = "SinRetornarAssuntos", partName = "SinRetornarAssuntos")
                    String sinRetornarAssuntos,
            @WebParam(name = "SinRetornarInteressados", partName = "SinRetornarInteressados")
                    String sinRetornarInteressados,
            @WebParam(name = "SinRetornarObservacoes", partName = "SinRetornarObservacoes")
                    String sinRetornarObservacoes,
            @WebParam(name = "SinRetornarAndamentoGeracao", partName = "SinRetornarAndamentoGeracao")
                    String sinRetornarAndamentoGeracao,
            @WebParam(name = "SinRetornarAndamentoConclusao", partName = "SinRetornarAndamentoConclusao")
                    String sinRetornarAndamentoConclusao,
            @WebParam(name = "SinRetornarUltimoAndamento", partName = "SinRetornarUltimoAndamento")
                    String sinRetornarUltimoAndamento,
            @WebParam(name = "SinRetornarUnidadesProcedimentoAberto", partName = "SinRetornarUnidadesProcedimentoAberto")
                    String sinRetornarUnidadesProcedimentoAberto,
            @WebParam(name = "SinRetornarProcedimentosRelacionados", partName = "SinRetornarProcedimentosRelacionados")
                    String sinRetornarProcedimentosRelacionados,
            @WebParam(name = "SinRetornarProcedimentosAnexados", partName = "SinRetornarProcedimentosAnexados")
                    String sinRetornarProcedimentosAnexados);

    /**
     * Consulta de processos individuais por usuario interessado
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param idOrgaoProcedimento
     * @param idTipoProcedimento
     * @param idOrgaoUsuario
     * @param siglaUsuario
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ProcedimentoResumido
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ProcedimentoResumido consultarProcedimentoIndividual(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdOrgaoProcedimento", partName = "IdOrgaoProcedimento")
                    String idOrgaoProcedimento,
            @WebParam(name = "IdTipoProcedimento", partName = "IdTipoProcedimento")
                    String idTipoProcedimento,
            @WebParam(name = "IdOrgaoUsuario", partName = "IdOrgaoUsuario")
                    String idOrgaoUsuario,
            @WebParam(name = "SiglaUsuario", partName = "SiglaUsuario")
                    String siglaUsuario);

    /**
     * Consulta de documentos
     * 
     * @param sinRetornarAndamentoGeracao
     * @param identificacaoServico
     * @param idUnidade
     * @param sinRetornarPublicacao
     * @param siglaSistema
     * @param sinRetornarCampos
     * @param sinRetornarAssinaturas
     * @param protocoloDocumento
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.RetornoConsultaDocumento
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public RetornoConsultaDocumento consultarDocumento(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloDocumento", partName = "ProtocoloDocumento")
                    String protocoloDocumento,
            @WebParam(name = "SinRetornarAndamentoGeracao", partName = "SinRetornarAndamentoGeracao")
                    String sinRetornarAndamentoGeracao,
            @WebParam(name = "SinRetornarAssinaturas", partName = "SinRetornarAssinaturas")
                    String sinRetornarAssinaturas,
            @WebParam(name = "SinRetornarPublicacao", partName = "SinRetornarPublicacao")
                    String sinRetornarPublicacao,
            @WebParam(name = "SinRetornarCampos", partName = "SinRetornarCampos")
                    String sinRetornarCampos);

    /**
     * Cancelamento de documentos
     * 
     * @param motivo
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloDocumento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String cancelarDocumento(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloDocumento", partName = "ProtocoloDocumento")
                    String protocoloDocumento,
            @WebParam(name = "Motivo", partName = "Motivo")
                    String motivo);

    /**
     * Geracao de bloco
     * 
     * @param tipo
     * @param documentos
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param unidadesDisponibilizacao
     * @param sinDisponibilizar
     * @param descricao
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String gerarBloco(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "Tipo", partName = "Tipo")
                    String tipo,
            @WebParam(name = "Descricao", partName = "Descricao")
                    String descricao,
            @WebParam(name = "UnidadesDisponibilizacao", partName = "UnidadesDisponibilizacao")
                    ArrayOfIdUnidade unidadesDisponibilizacao,
            @WebParam(name = "Documentos", partName = "Documentos")
                    ArrayOfDocumentoFormatado documentos,
            @WebParam(name = "SinDisponibilizar", partName = "SinDisponibilizar")
                    String sinDisponibilizar);

    /**
     * Consulta de bloco
     * 
     * @param idBloco
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param sinRetornarProtocolos
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.RetornoConsultaBloco
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public RetornoConsultaBloco consultarBloco(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdBloco", partName = "IdBloco")
                    String idBloco,
            @WebParam(name = "SinRetornarProtocolos", partName = "SinRetornarProtocolos")
                    String sinRetornarProtocolos);

    /**
     * Exclusao de bloco
     * 
     * @param idBloco
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String excluirBloco(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdBloco", partName = "IdBloco")
                    String idBloco);

    /**
     * Exclusao de processo
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String excluirProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento);

    /**
     * Exclusao de documento
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloDocumento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String excluirDocumento(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloDocumento", partName = "ProtocoloDocumento")
                    String protocoloDocumento);

    /**
     * Disponibilizacao de bloco
     * 
     * @param idBloco
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String disponibilizarBloco(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdBloco", partName = "IdBloco")
                    String idBloco);

    /**
     * Cancelamento de disponibilizacao de bloco
     * 
     * @param idBloco
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String cancelarDisponibilizacaoBloco(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdBloco", partName = "IdBloco")
                    String idBloco);

    /**
     * Inclusao de documento em bloco
     * 
     * @param idBloco
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param anotacao
     * @param protocoloDocumento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String incluirDocumentoBloco(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdBloco", partName = "IdBloco")
                    String idBloco,
            @WebParam(name = "ProtocoloDocumento", partName = "ProtocoloDocumento")
                    String protocoloDocumento,
            @WebParam(name = "Anotacao", partName = "Anotacao")
                    String anotacao);

    /**
     * Remocao de documento de bloco
     * 
     * @param idBloco
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloDocumento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String retirarDocumentoBloco(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdBloco", partName = "IdBloco")
                    String idBloco,
            @WebParam(name = "ProtocoloDocumento", partName = "ProtocoloDocumento")
                    String protocoloDocumento);

    /**
     * Inclusao de processo em bloco
     * 
     * @param idBloco
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param anotacao
     * @param protocoloProcedimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String incluirProcessoBloco(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdBloco", partName = "IdBloco")
                    String idBloco,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento,
            @WebParam(name = "Anotacao", partName = "Anotacao")
                    String anotacao);

    /**
     * Remocao de processo de bloco
     * 
     * @param idBloco
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String retirarProcessoBloco(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdBloco", partName = "IdBloco")
                    String idBloco,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento);

    /**
     * Reabertura de processo
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String reabrirProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento);

    /**
     * Conclusao de processo
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String concluirProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento);

    /**
     * Lista de extensoes de arquivos permitidas
     * 
     * @param identificacaoServico
     * @param idArquivoExtensao
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfArquivoExtensao
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfArquivoExtensao listarExtensoesPermitidas(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdArquivoExtensao", partName = "IdArquivoExtensao")
                    String idArquivoExtensao);

    /**
     * Movimentacao de processo entre unidades
     * 
     * @param sinReabrir
     * @param unidadesDestino
     * @param sinDiasUteisRetornoProgramado
     * @param identificacaoServico
     * @param sinRemoverAnotacao
     * @param idUnidade
     * @param sinManterAbertoUnidade
     * @param sinEnviarEmailNotificacao
     * @param dataRetornoProgramado
     * @param siglaSistema
     * @param diasRetornoProgramado
     * @param protocoloProcedimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String enviarProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento,
            @WebParam(name = "UnidadesDestino", partName = "UnidadesDestino")
                    ArrayOfIdUnidade unidadesDestino,
            @WebParam(name = "SinManterAbertoUnidade", partName = "SinManterAbertoUnidade")
                    String sinManterAbertoUnidade,
            @WebParam(name = "SinRemoverAnotacao", partName = "SinRemoverAnotacao")
                    String sinRemoverAnotacao,
            @WebParam(name = "SinEnviarEmailNotificacao", partName = "SinEnviarEmailNotificacao")
                    String sinEnviarEmailNotificacao,
            @WebParam(name = "DataRetornoProgramado", partName = "DataRetornoProgramado")
                    String dataRetornoProgramado,
            @WebParam(name = "DiasRetornoProgramado", partName = "DiasRetornoProgramado")
                    String diasRetornoProgramado,
            @WebParam(name = "SinDiasUteisRetornoProgramado", partName = "SinDiasUteisRetornoProgramado")
                    String sinDiasUteisRetornoProgramado,
            @WebParam(name = "SinReabrir", partName = "SinReabrir")
                    String sinReabrir);

    /**
     * Lista de usuarios com permissao na unidade
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param idUsuario
     * @param siglaSistema
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfUsuario
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfUsuario listarUsuarios(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdUsuario", partName = "IdUsuario")
                    String idUsuario);

    /**
     * Atribuicao de processo para usuario na unidade
     * 
     * @param sinReabrir
     * @param identificacaoServico
     * @param idUnidade
     * @param idUsuario
     * @param siglaSistema
     * @param protocoloProcedimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String atribuirProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento,
            @WebParam(name = "IdUsuario", partName = "IdUsuario")
                    String idUsuario,
            @WebParam(name = "SinReabrir", partName = "SinReabrir")
                    String sinReabrir);

    /**
     * Lista de hipoteses legais disponiveis
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param nivelAcesso
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfHipoteseLegal
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfHipoteseLegal listarHipotesesLegais(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "NivelAcesso", partName = "NivelAcesso")
                    String nivelAcesso);

    /**
     * Lista de paises disponiveis
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfPais
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfPais listarPaises(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade);

    /**
     * Lista de estados disponiveis
     * 
     * @param identificacaoServico
     * @param idPais
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfEstado
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfEstado listarEstados(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdPais", partName = "IdPais")
                    String idPais);

    /**
     * Lista de cidades disponiveis
     * 
     * @param idEstado
     * @param identificacaoServico
     * @param idPais
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfCidade
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfCidade listarCidades(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdPais", partName = "IdPais")
                    String idPais,
            @WebParam(name = "IdEstado", partName = "IdEstado")
                    String idEstado);

    /**
     * Lista de cargos disponiveis
     * 
     * @param idCargo
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfCargo
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfCargo listarCargos(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdCargo", partName = "IdCargo")
                    String idCargo);

    /**
     * Lista de tipos de conferencia disponiveis
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfTipoConferencia
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfTipoConferencia listarTiposConferencia(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade);

    /**
     * Adiciona um arquivo no repositorio
     * 
     * @param tamanho
     * @param conteudo
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param nome
     * @param hash
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String adicionarArquivo(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "Nome", partName = "Nome")
                    String nome,
            @WebParam(name = "Tamanho", partName = "Tamanho")
                    String tamanho,
            @WebParam(name = "Hash", partName = "Hash")
                    String hash,
            @WebParam(name = "Conteudo", partName = "Conteudo")
                    String conteudo);

    /**
     * Adiciona conteudo em um arquivo do repositorio
     * 
     * @param idArquivo
     * @param conteudo
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String adicionarConteudoArquivo(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdArquivo", partName = "IdArquivo")
                    String idArquivo,
            @WebParam(name = "Conteudo", partName = "Conteudo")
                    String conteudo);

    /**
     * Lanca andamento em processo
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param idTarefa
     * @param protocoloProcedimento
     * @param idTarefaModulo
     * @param atributos
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.Andamento
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public Andamento lancarAndamento(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento,
            @WebParam(name = "IdTarefa", partName = "IdTarefa")
                    String idTarefa,
            @WebParam(name = "IdTarefaModulo", partName = "IdTarefaModulo")
                    String idTarefaModulo,
            @WebParam(name = "Atributos", partName = "Atributos")
                    ArrayOfAtributoAndamento atributos);

    /**
     * Lista andamentos do processo
     * 
     * @param tarefasModulos
     * @param identificacaoServico
     * @param tarefas
     * @param idUnidade
     * @param siglaSistema
     * @param sinRetornarAtributos
     * @param protocoloProcedimento
     * @param andamentos
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfAndamento
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfAndamento listarAndamentos(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento,
            @WebParam(name = "SinRetornarAtributos", partName = "SinRetornarAtributos")
                    String sinRetornarAtributos,
            @WebParam(name = "Andamentos", partName = "Andamentos")
                    ArrayOfIdAndamentos andamentos,
            @WebParam(name = "Tarefas", partName = "Tarefas")
                    ArrayOfIdTarefas tarefas,
            @WebParam(name = "TarefasModulos", partName = "TarefasModulos")
                    ArrayOfIdTarefasModulo tarefasModulos);

    /**
     * Bloqueia processo
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String bloquearProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento);

    /**
     * Desbloqueia processo
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String desbloquearProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento);

    /**
     * Relaciona processos
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimento1
     * @param protocoloProcedimento2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String relacionarProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento1", partName = "ProtocoloProcedimento1")
                    String protocoloProcedimento1,
            @WebParam(name = "ProtocoloProcedimento2", partName = "ProtocoloProcedimento2")
                    String protocoloProcedimento2);

    /**
     * Remove relacionamento entre processos
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimento1
     * @param protocoloProcedimento2
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String removerRelacionamentoProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento1", partName = "ProtocoloProcedimento1")
                    String protocoloProcedimento1,
            @WebParam(name = "ProtocoloProcedimento2", partName = "ProtocoloProcedimento2")
                    String protocoloProcedimento2);

    /**
     * Sobrestar processo
     * 
     * @param protocoloProcedimentoVinculado
     * @param motivo
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String sobrestarProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento,
            @WebParam(name = "ProtocoloProcedimentoVinculado", partName = "ProtocoloProcedimentoVinculado")
                    String protocoloProcedimentoVinculado,
            @WebParam(name = "Motivo", partName = "Motivo")
                    String motivo);

    /**
     * Remover sobrestamento processo
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String removerSobrestamentoProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento);

    /**
     * Anexar processo
     * 
     * @param identificacaoServico
     * @param protocoloProcedimentoAnexado
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimentoPrincipal
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String anexarProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimentoPrincipal", partName = "ProtocoloProcedimentoPrincipal")
                    String protocoloProcedimentoPrincipal,
            @WebParam(name = "ProtocoloProcedimentoAnexado", partName = "ProtocoloProcedimentoAnexado")
                    String protocoloProcedimentoAnexado);

    /**
     * Desanexar processo
     * 
     * @param motivo
     * @param identificacaoServico
     * @param protocoloProcedimentoAnexado
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimentoPrincipal
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String desanexarProcesso(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimentoPrincipal", partName = "ProtocoloProcedimentoPrincipal")
                    String protocoloProcedimentoPrincipal,
            @WebParam(name = "ProtocoloProcedimentoAnexado", partName = "ProtocoloProcedimentoAnexado")
                    String protocoloProcedimentoAnexado,
            @WebParam(name = "Motivo", partName = "Motivo")
                    String motivo);

    /**
     * Lista marcadores da unidade
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfMarcador
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfMarcador listarMarcadoresUnidade(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade);

    /**
     * Define marcador em processos
     * 
     * @param identificacaoServico
     * @param idUnidade
     * @param siglaSistema
     * @param definicoes
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String definirMarcador(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "Definicoes", partName = "Definicoes")
                    ArrayOfDefinicaoMarcador definicoes);

    /**
     * Lista andamentos de marcadores do processo
     * 
     * @param identificacaoServico
     * @param marcadores
     * @param idUnidade
     * @param siglaSistema
     * @param protocoloProcedimento
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfAndamentoMarcador
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfAndamentoMarcador listarAndamentosMarcadores(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "ProtocoloProcedimento", partName = "ProtocoloProcedimento")
                    String protocoloProcedimento,
            @WebParam(name = "Marcadores", partName = "Marcadores")
                    ArrayOfIdMarcadores marcadores);

    /**
     * Consulta Publicacao
     * 
     * @param identificacaoServico
     * @param idDocumento
     * @param sinRetornarAndamento
     * @param idUnidade
     * @param siglaSistema
     * @param idPublicacao
     * @param sinRetornarAssinaturas
     * @param protocoloDocumento
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.RetornoConsultaPublicacao
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public RetornoConsultaPublicacao consultarPublicacao(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdPublicacao", partName = "IdPublicacao")
                    String idPublicacao,
            @WebParam(name = "IdDocumento", partName = "IdDocumento")
                    String idDocumento,
            @WebParam(name = "ProtocoloDocumento", partName = "ProtocoloDocumento")
                    String protocoloDocumento,
            @WebParam(name = "SinRetornarAndamento", partName = "SinRetornarAndamento")
                    String sinRetornarAndamento,
            @WebParam(name = "SinRetornarAssinaturas", partName = "SinRetornarAssinaturas")
                    String sinRetornarAssinaturas);

    /**
     * Agenda Publicacao
     * 
     * @param dataDisponibilizacao
     * @param identificacaoServico
     * @param idDocumento
     * @param idVeiculoPublicacao
     * @param idUnidade
     * @param siglaSistema
     * @param staMotivo
     * @param resumo
     * @param imprensaNacional
     * @param protocoloDocumento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String agendarPublicacao(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdDocumento", partName = "IdDocumento")
                    String idDocumento,
            @WebParam(name = "ProtocoloDocumento", partName = "ProtocoloDocumento")
                    String protocoloDocumento,
            @WebParam(name = "StaMotivo", partName = "StaMotivo")
                    String staMotivo,
            @WebParam(name = "IdVeiculoPublicacao", partName = "IdVeiculoPublicacao")
                    String idVeiculoPublicacao,
            @WebParam(name = "DataDisponibilizacao", partName = "DataDisponibilizacao")
                    String dataDisponibilizacao,
            @WebParam(name = "Resumo", partName = "Resumo")
                    String resumo,
            @WebParam(name = "ImprensaNacional", partName = "ImprensaNacional")
                    PublicacaoImprensaNacional imprensaNacional);

    /**
     * Altera dados da Publicacao
     * 
     * @param dataDisponibilizacao
     * @param identificacaoServico
     * @param idDocumento
     * @param idVeiculoPublicacao
     * @param idUnidade
     * @param siglaSistema
     * @param idPublicacao
     * @param staMotivo
     * @param resumo
     * @param imprensaNacional
     * @param protocoloDocumento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String alterarPublicacao(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdPublicacao", partName = "IdPublicacao")
                    String idPublicacao,
            @WebParam(name = "IdDocumento", partName = "IdDocumento")
                    String idDocumento,
            @WebParam(name = "ProtocoloDocumento", partName = "ProtocoloDocumento")
                    String protocoloDocumento,
            @WebParam(name = "StaMotivo", partName = "StaMotivo")
                    String staMotivo,
            @WebParam(name = "IdVeiculoPublicacao", partName = "IdVeiculoPublicacao")
                    String idVeiculoPublicacao,
            @WebParam(name = "DataDisponibilizacao", partName = "DataDisponibilizacao")
                    String dataDisponibilizacao,
            @WebParam(name = "Resumo", partName = "Resumo")
                    String resumo,
            @WebParam(name = "ImprensaNacional", partName = "ImprensaNacional")
                    PublicacaoImprensaNacional imprensaNacional);

    /**
     * Cancela Agendamento da Publicacao
     * 
     * @param identificacaoServico
     * @param idDocumento
     * @param idUnidade
     * @param siglaSistema
     * @param idPublicacao
     * @param protocoloDocumento
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String cancelarAgendamentoPublicacao(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdPublicacao", partName = "IdPublicacao")
                    String idPublicacao,
            @WebParam(name = "IdDocumento", partName = "IdDocumento")
                    String idDocumento,
            @WebParam(name = "ProtocoloDocumento", partName = "ProtocoloDocumento")
                    String protocoloDocumento);

    /**
     * Lista Feriados
     * 
     * @param identificacaoServico
     * @param idOrgao
     * @param idUnidade
     * @param siglaSistema
     * @param dataInicial
     * @param dataFinal
     * @return
     *     returns org.opensingular.server.connector.sei31.ws.ArrayOfFeriado
     */
    @WebMethod(action = "SeiAction")
    @WebResult(name = "parametros", partName = "parametros")
    public ArrayOfFeriado listarFeriados(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdUnidade", partName = "IdUnidade")
                    String idUnidade,
            @WebParam(name = "IdOrgao", partName = "IdOrgao")
                    String idOrgao,
            @WebParam(name = "DataInicial", partName = "DataInicial")
                    String dataInicial,
            @WebParam(name = "DataFinal", partName = "DataFinal")
                    String dataFinal);

    /**
     * Confirma Disponibilização das Publicações
     * 
     * @param dataDisponibilizacao
     * @param identificacaoServico
     * @param numero
     * @param idVeiculoPublicacao
     * @param siglaSistema
     * @param dataPublicacao
     * @param idDocumentos
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "SeiPublicacaoAction")
    @WebResult(name = "parametros", partName = "parametros")
    public String confirmarDisponibilizacaoPublicacao(
            @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
                    String siglaSistema,
            @WebParam(name = "IdentificacaoServico", partName = "IdentificacaoServico")
                    String identificacaoServico,
            @WebParam(name = "IdVeiculoPublicacao", partName = "IdVeiculoPublicacao")
                    String idVeiculoPublicacao,
            @WebParam(name = "DataDisponibilizacao", partName = "DataDisponibilizacao")
                    String dataDisponibilizacao,
            @WebParam(name = "DataPublicacao", partName = "DataPublicacao")
                    String dataPublicacao,
            @WebParam(name = "Numero", partName = "Numero")
                    String numero,
            @WebParam(name = "IdDocumentos", partName = "IdDocumentos")
                    ArrayOfIdDocumento idDocumentos);

}
