
/*
 * Copyright (C) 2016 Singular Studios (a.k.a Atom Tecnologia) - www.opensingular.com
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opensingular.requirement.sip.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "sipPortType", targetNamespace = "sipns")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SipPortType {


    /**
     * 
     * @param senha
     * @param sigla
     * @param idOrgao
     * @param idContexto
     * @return
     *     returns boolean
     */
    @WebMethod(action = "sipnsAction")
    @WebResult(name = "returnAutenticar", partName = "returnAutenticar")
    public boolean autenticar(
        @WebParam(name = "IdOrgao", partName = "IdOrgao")
        String idOrgao,
        @WebParam(name = "IdContexto", partName = "IdContexto")
        String idContexto,
        @WebParam(name = "Sigla", partName = "Sigla")
        String sigla,
        @WebParam(name = "Senha", partName = "Senha")
        String senha);

    /**
     * 
     * @param senha
     * @param siglaOrgaoSistema
     * @param sigla
     * @param idOrgao
     * @param siglaSistema
     * @return
     *     returns org.opensingular.sip.RetornoAutenticarCompleto
     */
    @WebMethod(action = "sipnsAction")
    @WebResult(name = "returnAutenticarCompleto", partName = "returnAutenticarCompleto")
    public RetornoAutenticarCompleto autenticarCompleto(
        @WebParam(name = "IdOrgao", partName = "IdOrgao")
        String idOrgao,
        @WebParam(name = "Sigla", partName = "Sigla")
        String sigla,
        @WebParam(name = "Senha", partName = "Senha")
        String senha,
        @WebParam(name = "SiglaSistema", partName = "SiglaSistema")
        String siglaSistema,
        @WebParam(name = "SiglaOrgaoSistema", partName = "SiglaOrgaoSistema")
        String siglaOrgaoSistema);

    /**
     * 
     * @param idSistema
     * @param idUsuario
     * @param hashAgente
     * @param idLogin
     * @return
     *     returns org.opensingular.sip.RetornoValidarLogin
     */
    @WebMethod(action = "sipnsAction")
    @WebResult(name = "returnLogin", partName = "returnLogin")
    public RetornoValidarLogin validarLogin(
        @WebParam(name = "IdLogin", partName = "IdLogin")
        String idLogin,
        @WebParam(name = "IdSistema", partName = "IdSistema")
        long idSistema,
        @WebParam(name = "IdUsuario", partName = "IdUsuario")
        long idUsuario,
        @WebParam(name = "HashAgente", partName = "HashAgente")
        String hashAgente);

}
