CREATE SEQUENCE DBSINGULAR.SQ_CO_DESTINATARIO_EMAIL  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE DBSINGULAR.SQ_CO_EMAIL  START WITH 1 INCREMENT BY 1;

ALTER TABLE DBSINGULAR.TB_DESTINATARIO_EMAIL ALTER COLUMN CO_DESTINATARIO_EMAIL INTEGER NOT NULL;
ALTER TABLE DBSINGULAR.TB_EMAIL ALTER COLUMN CO_EMAIL INTEGER NOT NULL;