<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- 

 Este Wsdl foi modificado.

- troquei o use="encoded" por use="literal" nas operações.
- retirei todas as operações e messages pois não estava com os tipos de retorno. Deixei apenas a operação autenticar que utilizamos.

 -->
<wsdl:definitions name="SipWS" 
			 targetNamespace="sipns"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:tns="sipns">


  <wsdl:message name="autenticarRequest">
    <wsdl:part name="IdOrgao" type="xsd:string" />
    <wsdl:part name="IdContexto" type="xsd:string" />
    <wsdl:part name="Sigla" type="xsd:string" />
    <wsdl:part name="Senha" type="xsd:string" />
  </wsdl:message>

  <wsdl:message name="autenticarResponse">
    <wsdl:part name="returnAutenticar" type="xsd:boolean"/>
  </wsdl:message>
  
  <wsdl:portType name="sipPortType">
   <wsdl:operation name="autenticar">
      <wsdl:input message="tns:autenticarRequest"/>
      <wsdl:output message="tns:autenticarResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="sipBinding" type="tns:sipPortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

    <wsdl:operation name="autenticar">
      <soap:operation soapAction="sipnsAction"/>
      <wsdl:input>
        <soap:body namespace="sipns" use="literal" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body namespace="sipns" use="literal" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="sipService">
    <wsdl:port name="sipPortType" binding="tns:sipBinding">
      <soap:address location="http://treinamentosei3singular.antaq.gov.br/sip/ws/SipWS.php"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
